[ids]

*

[main]

capslock = overload(capslock_layer, esc)

[capslock_layer]

backspace = delete

# arrow keys vi sytle
h = left
j = down
k = up
l = right

# f keys
1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
0 = f10
minus = f11
equal = f12

[capslock_layer+shift]

h = home
l = end
j = pagedown
k = pageup
