# Based on https://github.com/yassinebridi/tmux-purpura
bg_main="#ffffff"
fg_main="#24292f"

bg_secondary="#e3e4e6"
fg_secondary="#24292f"

blue="#218bff"
light_blue="#f2f4f7"
orange="#fe640b"

# base
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length 80
set-option -g status-right-style none
set-option -g status-right-length 80
set-window-option -g window-status-separator " "

# pane border styling
set-option -g pane-active-border-style "fg=${blue}"
set-option -g pane-border-style "fg=${bg_secondary}"

# message styling
set-option -g message-style "bg=${light_blue},fg=${blue}"

# status bar
set-option -g status-style "bg=${bg_main},fg=${fg_main}"

set-option -g status-left "#[fg=${bg_main},bg=${fg_main}] #S " # path
set-option -ga status-left "#[bg=${bg_main},fg=${fg_main},nobold,noitalics,nounderscore] " # space before window tabs

set-option -g  status-right "#[bg=${bg_secondary},fg=${fg_secondary}] %d/%m %H:%M | #(~/home/scripts/power_mode.sh) | #(~/home/scripts/battery.sh) "
set-option -ga status-right "#[fg=${bg_main},bg=${fg_main}] #h "

# window tabs 
set-window-option -g window-status-current-format "#[fg=${light_blue},bg=${blue}] #I｜#[bold]#W#{?window_zoomed_flag,*Z,} "
set-window-option -g window-status-format "#[fg=${fg_secondary}]#[bg=${bg_secondary}] #I｜#W#{?window_zoomed_flag,*Z,} "

# copy-highlight
set-window-option -g mode-style "bg=${blue},fg=${light_blue}"
